name: Ruff

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: Run Ruff check
        run: uv run ruff check --fix

      - name: Run Ruff format
        run: uv run ruff format .
