name: ruff check and format

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh

      - name: install ruff
        run: uv tool install ruff

      - name: ruff check --fix
        run: ruff check --fix

      - name: ruff format
        run: ruff format .
